### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by sgmccalla** [phoenixding/scdiff#1]
SCDIFF works for a while, then I receive the error below. I am not sure how to resolve this. Any help is appreciated, thank you.

Input:
```
scdiff -i analysis1_scdiff_input.txt -t prediction_k100.txt -k auto -o scdiff_out
```

Error:
```
cell:1979
cell:1980
cell:1981
cell:0
learning K...
Traceback (most recent call last):
  File "/usr/local/bin/scdiff", line 9, in <module>
    load_entry_point('scdiff==1.1.12', 'console_scripts', 'scdiff')()
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 1571, in main
    G1=Graph(AllCells,tfdna,kc,largeType,dsync,virtualAncestor,fChangeCut)
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 776, in __init__
    self.Nodes=self.buildNodes()							# build nodees based on cells
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 831, in buildNodes
    return(self.clustering.performClustering())
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 324, in performClustering
    [dCK,dBS]=self.getClusteringPars()
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 82, in getClusteringPars
    dCK=self.getdCK(self.kc)                                      # number of clusters for each time point, director
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 138, in getdCK
    dCK = self.determineK(K0=1)
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 257, in determineK
    pn = bestK(T)
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 167, in bestK
    CS = detPeak(K, ST, 0.1)
  File "/Users/sg/Library/Python/2.7/lib/python/site-packages/scdiff/scdiff.py", line 1297, in detPeak
    minA=max(0,min(A))
ValueError: min() arg is an empty sequence
```

**Comment by phoenixding** [comment]
@sgmccalla 

Thanks for reporting this error. 

How many cells you have in your input?  
Not sure why the cell index goes from 'cell:1981' to 'cell:0' in your error log, is it a typo or the one from the actual output? 

This seems caused by a special case (empty list of silhouette scores for one of the time points). 
I tried to add a few lines of exception handling codes, which can probably solve the problem you encountered (also, please make sure that your input expression file format is correct, remove empty rows if there're any). 

Let me know if the problem still exists using the updated code (please re-download the updated  package)
