### ISSUE TITLE
issue with auto run

### ISSUE THREAD

**Issue by menghandu** [phoenixding/scdiff#2]
Hi!
Thanks for sharing this useful tool with us! Here I am interested in analyzing some single cell RNA-seq with SCDIFF but now I got an error which I don't know how to deal with.
  
   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 347, in kneighbors (train_size, n_neighbors)

   ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 6

May I get your help with it?
Best,
Meghan

**Comment by phoenixding** [comment]
@menghandu 

Thanks for reporting this issue. 
It seems that you only have 2 samples but the program asks for 6 neighbors. 
The problem could potentially relate to the diffusion map analysis, but I am not sure. 
Could you please post your complete error log? It would be helpful for me to locate the problem. 
Thanks.

**Comment by menghandu** [comment]
/Users/Candice/Dropbox/Screenshots/Screenshot 2018-05-29 09.33.19.png
Hi!
I appreciate your quick reply! Here attached is the error I got.
Thanks for your kind help!
Meghan

**Comment by menghandu** [comment]
Hi!
I appreciate your quick reply! Here is the error I got.

clustering for time: 0.0
clustering for time: 2.0
clustering for time: 5.0
clustering for time: 20.0
clustering for time: 22.0
building graph...
time adjustment...
connecting nodes ....
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/scdiff", line 11, in <module>
    load_entry_point('scdiff==1.1.15', 'console_scripts', 'scdiff')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdiff/scdiff.py", line 1672, in main
    G1=Graph(AllCells,tfdna,kc,largeType,dsync,virtualAncestor,fChangeCut,etf)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdiff/scdiff.py", line 779, in __init__
    self.Edges = self.buildEdges()  # build edges based on nodes
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdiff/scdiff.py", line 1050, in buildEdges
    p1 = Path(i.P, i,self.Nodes,self.dTD,self.dTG,self.dMb,self.fChangeCut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdiff/scdiff.py", line 576, in __init__
    self.B=self.getTransition(dTD,dTG,dMb,fChangeCut)                       # transition offset
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdiff/scdiff.py", line 696, in getTransition
    [X, Y,U,D] = buildTrain(G, dTG, etfID,self.GL,FCUT)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdiff/scdiff.py", line 1520, in buildTrain
    Xs,Ys=sm.fit_sample(X,Y)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imblearn/base.py", line 88, in fit_sample
    return self.fit(X, y).sample(X, y)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imblearn/base.py", line 64, in sample
    return self._sample(X, y)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imblearn/over_sampling/smote.py", line 594, in _sample
    return self._sample_regular(X, y)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imblearn/over_sampling/smote.py", line 360, in _sample_regular
    nns = self.nn_k_.kneighbors(X_class, return_distance=False)[:, 1:]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 347, in kneighbors
    (train_size, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 6


Thanks for your kind help!
Meghan

**Comment by phoenixding** [comment]
@menghandu 

Thanks. I see the problem now.  (it's a bug in the imbalanced training package I am using, called smote)
I'll get it fixed as soon as I can, hopefully sometime this week. Sorry for the inconvenience it caused. 
I'll keep you posted.

**Comment by phoenixding** [comment]
@menghandu 

Hi, 

I just fixed the SMOTE bug, it should solve the problem you reported.
please download the latest update. Let me know if the problem persists. Thanks.

**Comment by GGboy-Zzz** [comment]
The problem persists in the latest version. @phoenixding 

<img width="1306" height="676" alt="Image" src="https://github.com/user-attachments/assets/9d8c2151-b464-4bb2-97a4-430314ed44b4" />
